### ISSUE TITLE
Allow Link to Specify Target MIDI Device

### ISSUE THREAD

**Issue by JayShoe** [benc-uk/touchmidi#1]
Hello Ben, 

Thanks for your project! I'm making a digital audio mixer and I've been using the old version. I'm now updating to the new version. Looks great!

On the old version I was able to specify the name of the MIDI device in the link to the page, so that I can preselect a MIDI device. 	

This would automatically locate the "Teensy MIDI Audio" device. 
`<a class="menu" href="index.html?device=Teensy%20MIDI/Audio">VOLUME (I2C)</a>
`
I use this because I created a menu up top of the page that calls up the i2c mixer, dsp mixer, effect controls, etc. Each page focuses on a particular component of the mixer. 

The newer version doesn't support this. How can we preselect a MIDI device on the page, or in the URL? Any idea? (I realize this is a feature not a bug). 

I would love to be able to preselect a device upon load (for hardcoding a device), or possibly the option to select the device once and then every page afterwards would select the same device that's already been selected?

Thanks again!
Jay

**Comment by benc-uk** [comment]
Hey thanks for checking my project out!
Yeah this was a regression from the old version

I've added support for it now, see https://github.com/benc-uk/touchmidi#advanced-usage
It works by device id rather than name, which means with multiple devices, the order might change, but it's rare enough to be an edge case I think.

The v2.1.0 release has this feature

**Comment by JayShoe** [comment]
Awesome thanks! I will check it out.

`channel=<channel_num>- Set the channel (1 - 16) to use, if not provided channel 1 is used.'

My project is multi-channel. I will test, but hopefully it can default to "set per layout".

**Comment by benc-uk** [comment]
Ahh yes, good point!
Channel 0 is a what I use to denote multi-channel. So if you set `channel=0` it will use the channels set in the layout
I forgot to include this in the readme!

**Comment by JayShoe** [comment]
Hi Ben, 

Sorry to bother you, but I have an additional request.

Is there any way to get this to work as it did in V1 where one can specify the device NAME instead of "output-1", "output-2"? (IE "device name", "korg keyboard", "Teensy Midi/Audio", etc. 

I have the ability to name my device whatever I want, but I can't predetermine what other midi devices the computer has on the machine. So without the ability to call a device by name, I can't reliably use this. 

Thanks for your consideration.

Jay
