### ISSUE TITLE
Enhancement - Support for Pitch Bend

### ISSUE THREAD

**Issue by rockumk** [benc-uk/touchmidi#2]
Please consider adding support for Pitch Bend.

**Comment by benc-uk** [comment]
Good idea, I thought it was possible with CC but it's own message type

**Comment by rockumk** [comment]
Thank you for taking a look.

**Comment by benc-uk** [comment]
Added in v2.2.0

I think the CDN is caching old versions I don't know why, you'll have to add @v2.2.0 to the script tag

Closed by commit 99c92f54931d835953810a3adc1831b175ed4fa1

**Comment by rockumk** [comment]
Not sure I know what that means, but I will try to figure it out. I mainly wanted to say thanks again!

**Comment by benc-uk** [comment]
Sorry I wasn't very clear, make sure your script tag in your HTML looks like this 

```html
<script src="https://cdn.jsdelivr.net/gh/benc-uk/touchmidi@v2.2.0/dist/bundle.js"></script>
```
Where the part `@v2.2.0` goes after the touchmidi part - this forces it to fetch that exact version

Thanks again for trying out my project, I hope you find it useful!

**Comment by rockumk** [comment]
Ok thanks again!
